sudo: false
language: ruby
rvm:
  - 2.3.1
  - 2.2
  - 2.4.0-preview1
matrix:
  allow_failures:
  - rvm: 2.4.0-preview1

before_install: gem install bundler -v 1.12.5
script: bundle exec rake spec SPEC_OPTS="--format p"
addons:
  code_climate:
    repo_token: 65276d9bbeb1bc990342faa04d89bfc4a84534329cee34bc5b7c513e4f6c3e3e
