sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0-p648
  - ruby-head
  - jruby-9.1.5.0
  - jruby-head

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head

before_install: gem install bundler -v 1.14.6
script: bundle exec rake spec SPEC_OPTS="--format p"
addons:
  code_climate:
    repo_token: 65276d9bbeb1bc990342faa04d89bfc4a84534329cee34bc5b7c513e4f6c3e3e
